# Initialize

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 25, 1) # numpy.arange([start, ] stop, [step, ] dtype=None)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# Shape

## Checking the shape

In [3]:
arr.shape

(24,)

In [4]:
np.shape(arr)

(24,)

## Reshape

In [5]:
arr2d = np.reshape(arr, (4, 6))

In [6]:
arr2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [8]:
np.shape(arr2d)

(4, 6)

In [9]:
arr3d = np.reshape(arr, (4, 3, 2))

In [10]:
arr3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [11]:
arr3d[0]

array([[1, 2],
       [3, 4],
       [5, 6]])